### ISSUE TITLE
Roadmap 2 Version 1

### ISSUE THREAD

**Issue by schmidtfa** [schmidtfa/AlmKanal#1]
Feature List
- [x] Define sensible defaults
- [ ] Add individual MRI support
- [ ] Add basic TRF preprocessing
- [ ] Add obob_mne mixins
- [ ] build data loaders (should cover bids format and our local salzburg data) 

Documentation
- [ ]  Make PyRASA style Documentation website
- [ ] Add Classic Template Pipelines
- [x] Add Code Documentation
